{"level":"error","message":"Could not connect to MongoDB at mongodb://host.docker.internal:27017/tweets","error":{"message":"Could not connect to MongoDB at mongodb://host.docker.internal:27017/tweets","stack":"Error: Could not connect to MongoDB at mongodb://host.docker.internal:27017/tweets\n    at NativeConnection.SafeMongooseConnection.onError (/dist/src/lib/safe-mongoose-connection.js:57:31)\n    at NativeConnection.emit (events.js:400:28)\n    at /node_modules/mongoose/lib/connection.js:856:30\n    at processTicksAndRejections (internal/process/task_queues.js:77:11)"},"service":"api","timestamp":"2022-01-09T14:22:56.206Z"}
{"level":"error","message":"Could not connect to MongoDB at mongodb://host.docker.internal:27017/tweets","error":{"message":"Could not connect to MongoDB at mongodb://host.docker.internal:27017/tweets","stack":"Error: Could not connect to MongoDB at mongodb://host.docker.internal:27017/tweets\n    at NativeConnection.SafeMongooseConnection.onError (/dist/src/lib/safe-mongoose-connection.js:57:31)\n    at NativeConnection.emit (events.js:400:28)\n    at /node_modules/mongoose/lib/connection.js:856:30\n    at processTicksAndRejections (internal/process/task_queues.js:77:11)"},"service":"api","timestamp":"2022-01-09T14:23:28.186Z"}
{"level":"error","message":"Could not connect to MongoDB at mongodb://host.docker.internal:27017/tweets","error":{"message":"Could not connect to MongoDB at mongodb://host.docker.internal:27017/tweets","stack":"Error: Could not connect to MongoDB at mongodb://host.docker.internal:27017/tweets\n    at NativeConnection.SafeMongooseConnection.onError (/dist/src/lib/safe-mongoose-connection.js:57:31)\n    at NativeConnection.emit (events.js:400:28)\n    at /node_modules/mongoose/lib/connection.js:856:30\n    at processTicksAndRejections (internal/process/task_queues.js:77:11)"},"service":"api","timestamp":"2022-01-09T14:24:00.163Z"}
{"level":"error","message":"Could not connect to MongoDB at mongodb://host.docker.internal:27017/tweets","error":{"message":"Could not connect to MongoDB at mongodb://host.docker.internal:27017/tweets","stack":"Error: Could not connect to MongoDB at mongodb://host.docker.internal:27017/tweets\n    at NativeConnection.SafeMongooseConnection.onError (/dist/src/lib/safe-mongoose-connection.js:57:31)\n    at NativeConnection.emit (events.js:400:28)\n    at /node_modules/mongoose/lib/connection.js:856:30\n    at processTicksAndRejections (internal/process/task_queues.js:77:11)"},"service":"api","timestamp":"2022-01-09T14:24:32.140Z"}
{"level":"error","message":"Could not connect to MongoDB at mongodb://host.docker.internal:27017/tweets","error":{"message":"Could not connect to MongoDB at mongodb://host.docker.internal:27017/tweets","stack":"Error: Could not connect to MongoDB at mongodb://host.docker.internal:27017/tweets\n    at NativeConnection.SafeMongooseConnection.onError (/dist/src/lib/safe-mongoose-connection.js:57:31)\n    at NativeConnection.emit (events.js:400:28)\n    at /node_modules/mongoose/lib/connection.js:856:30\n    at processTicksAndRejections (internal/process/task_queues.js:77:11)"},"service":"api","timestamp":"2022-01-09T14:25:04.116Z"}
{"level":"error","message":"Could not connect to MongoDB at mongodb://host.docker.internal:27017/tweets","error":{"message":"Could not connect to MongoDB at mongodb://host.docker.internal:27017/tweets","stack":"Error: Could not connect to MongoDB at mongodb://host.docker.internal:27017/tweets\n    at NativeConnection.SafeMongooseConnection.onError (/dist/src/lib/safe-mongoose-connection.js:57:31)\n    at NativeConnection.emit (events.js:400:28)\n    at /node_modules/mongoose/lib/connection.js:856:30\n    at processTicksAndRejections (internal/process/task_queues.js:77:11)"},"service":"api","timestamp":"2022-01-09T14:25:36.063Z"}
{"level":"error","message":"Could not connect to MongoDB at mongodb://host.docker.internal:27017/tweets","error":{"message":"Could not connect to MongoDB at mongodb://host.docker.internal:27017/tweets","stack":"Error: Could not connect to MongoDB at mongodb://host.docker.internal:27017/tweets\n    at NativeConnection.SafeMongooseConnection.onError (/dist/src/lib/safe-mongoose-connection.js:57:31)\n    at NativeConnection.emit (events.js:400:28)\n    at /node_modules/mongoose/lib/connection.js:856:30\n    at processTicksAndRejections (internal/process/task_queues.js:77:11)"},"service":"api","timestamp":"2022-01-09T14:26:08.040Z"}
{"level":"error","message":"Could not connect to MongoDB at mongodb://host.docker.internal:27017/tweets","error":{"message":"Could not connect to MongoDB at mongodb://host.docker.internal:27017/tweets","stack":"Error: Could not connect to MongoDB at mongodb://host.docker.internal:27017/tweets\n    at NativeConnection.SafeMongooseConnection.onError (/dist/src/lib/safe-mongoose-connection.js:57:31)\n    at NativeConnection.emit (events.js:400:28)\n    at /node_modules/mongoose/lib/connection.js:856:30\n    at processTicksAndRejections (internal/process/task_queues.js:77:11)"},"service":"api","timestamp":"2022-01-09T14:26:40.016Z"}
{"level":"error","message":"Could not connect to MongoDB at mongodb://host.docker.internal:27017/tweets","error":{"message":"Could not connect to MongoDB at mongodb://host.docker.internal:27017/tweets","stack":"Error: Could not connect to MongoDB at mongodb://host.docker.internal:27017/tweets\n    at NativeConnection.SafeMongooseConnection.onError (/dist/src/lib/safe-mongoose-connection.js:57:31)\n    at NativeConnection.emit (events.js:400:28)\n    at /node_modules/mongoose/lib/connection.js:856:30\n    at processTicksAndRejections (internal/process/task_queues.js:77:11)"},"service":"api","timestamp":"2022-01-09T14:27:11.995Z"}
{"level":"error","message":"Could not connect to MongoDB at mongodb://host.docker.internal:27017/tweets","error":{"message":"Could not connect to MongoDB at mongodb://host.docker.internal:27017/tweets","stack":"Error: Could not connect to MongoDB at mongodb://host.docker.internal:27017/tweets\n    at NativeConnection.SafeMongooseConnection.onError (/dist/src/lib/safe-mongoose-connection.js:57:31)\n    at NativeConnection.emit (events.js:400:28)\n    at /node_modules/mongoose/lib/connection.js:856:30\n    at processTicksAndRejections (internal/process/task_queues.js:77:11)"},"service":"api","timestamp":"2022-01-09T14:27:43.972Z"}
{"level":"error","message":"Could not connect to MongoDB at mongodb://host.docker.internal:27017/tweets","error":{"message":"Could not connect to MongoDB at mongodb://host.docker.internal:27017/tweets","stack":"Error: Could not connect to MongoDB at mongodb://host.docker.internal:27017/tweets\n    at NativeConnection.SafeMongooseConnection.onError (/dist/src/lib/safe-mongoose-connection.js:57:31)\n    at NativeConnection.emit (events.js:400:28)\n    at /node_modules/mongoose/lib/connection.js:856:30\n    at processTicksAndRejections (internal/process/task_queues.js:77:11)"},"service":"api","timestamp":"2022-01-09T14:28:15.952Z"}
{"level":"error","message":"Could not connect to MongoDB at mongodb://host.docker.internal:27017/tweets","error":{"message":"Could not connect to MongoDB at mongodb://host.docker.internal:27017/tweets","stack":"Error: Could not connect to MongoDB at mongodb://host.docker.internal:27017/tweets\n    at NativeConnection.SafeMongooseConnection.onError (/dist/src/lib/safe-mongoose-connection.js:57:31)\n    at NativeConnection.emit (events.js:400:28)\n    at /node_modules/mongoose/lib/connection.js:856:30\n    at processTicksAndRejections (internal/process/task_queues.js:77:11)"},"service":"api","timestamp":"2022-01-09T14:28:47.930Z"}
{"level":"error","message":"Could not connect to MongoDB at mongodb://host.docker.internal:27017/tweets","error":{"message":"Could not connect to MongoDB at mongodb://host.docker.internal:27017/tweets","stack":"Error: Could not connect to MongoDB at mongodb://host.docker.internal:27017/tweets\n    at NativeConnection.SafeMongooseConnection.onError (/dist/src/lib/safe-mongoose-connection.js:57:31)\n    at NativeConnection.emit (events.js:400:28)\n    at /node_modules/mongoose/lib/connection.js:856:30\n    at processTicksAndRejections (internal/process/task_queues.js:77:11)"},"service":"api","timestamp":"2022-01-09T14:29:19.909Z"}
{"level":"error","message":"Could not connect to MongoDB at mongodb://host.docker.internal:27017/tweets","error":{"message":"Could not connect to MongoDB at mongodb://host.docker.internal:27017/tweets","stack":"Error: Could not connect to MongoDB at mongodb://host.docker.internal:27017/tweets\n    at NativeConnection.SafeMongooseConnection.onError (/dist/src/lib/safe-mongoose-connection.js:57:31)\n    at NativeConnection.emit (events.js:400:28)\n    at /node_modules/mongoose/lib/connection.js:856:30\n    at processTicksAndRejections (internal/process/task_queues.js:77:11)"},"service":"api","timestamp":"2022-01-09T14:29:51.887Z"}
{"level":"error","message":"Could not connect to MongoDB at mongodb://host.docker.internal:27017/tweets","error":{"message":"Could not connect to MongoDB at mongodb://host.docker.internal:27017/tweets","stack":"Error: Could not connect to MongoDB at mongodb://host.docker.internal:27017/tweets\n    at NativeConnection.SafeMongooseConnection.onError (/dist/src/lib/safe-mongoose-connection.js:57:31)\n    at NativeConnection.emit (events.js:400:28)\n    at /node_modules/mongoose/lib/connection.js:856:30\n    at processTicksAndRejections (internal/process/task_queues.js:77:11)"},"service":"api","timestamp":"2022-01-09T14:30:23.873Z"}
{"level":"error","message":"Could not connect to MongoDB at mongodb://host.docker.internal:27017/tweets","error":{"message":"Could not connect to MongoDB at mongodb://host.docker.internal:27017/tweets","stack":"Error: Could not connect to MongoDB at mongodb://host.docker.internal:27017/tweets\n    at NativeConnection.SafeMongooseConnection.onError (/dist/src/lib/safe-mongoose-connection.js:57:31)\n    at NativeConnection.emit (events.js:400:28)\n    at /node_modules/mongoose/lib/connection.js:856:30\n    at processTicksAndRejections (internal/process/task_queues.js:77:11)"},"service":"api","timestamp":"2022-01-09T14:30:55.852Z"}
{"level":"error","message":"Could not connect to MongoDB at mongodb://host.docker.internal:27017/tweets","error":{"message":"Could not connect to MongoDB at mongodb://host.docker.internal:27017/tweets","stack":"Error: Could not connect to MongoDB at mongodb://host.docker.internal:27017/tweets\n    at NativeConnection.SafeMongooseConnection.onError (/dist/src/lib/safe-mongoose-connection.js:57:31)\n    at NativeConnection.emit (events.js:400:28)\n    at /node_modules/mongoose/lib/connection.js:856:30\n    at processTicksAndRejections (internal/process/task_queues.js:77:11)"},"service":"api","timestamp":"2022-01-09T14:31:27.827Z"}
{"level":"error","message":"Could not connect to MongoDB at mongodb://host.docker.internal:27017/tweets","error":{"message":"Could not connect to MongoDB at mongodb://host.docker.internal:27017/tweets","stack":"Error: Could not connect to MongoDB at mongodb://host.docker.internal:27017/tweets\n    at NativeConnection.SafeMongooseConnection.onError (/dist/src/lib/safe-mongoose-connection.js:57:31)\n    at NativeConnection.emit (events.js:400:28)\n    at /node_modules/mongoose/lib/connection.js:856:30\n    at processTicksAndRejections (internal/process/task_queues.js:77:11)"},"service":"api","timestamp":"2022-01-09T14:31:59.803Z"}
